/*
SELECT STARNAME
FROM STARSIN
WHERE MOVIEYEAR = '1980' OR MOVIETITLE LIKE '%Knight%';*/


/*SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH>10000000;*/

/*SELECT NAME
FROM MOVIESTAR
WHERE GENDER='M' OR ADDRESS='Prefect Rd.';*/

